package com.tijiebo.woofwoof.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val lightPrimary = Color(0xFF275EA7)
private val lightOnPrimary = Color(0xFFFFFFFF)
private val lightPrimaryContainer = Color(0xFFD6E3FF)
private val lightOnPrimaryContainer = Color(0xFF001B3D)
private val lightSecondary = Color(0xFF225FA6)
private val lightOnSecondary = Color(0xFFFFFFFF)
private val lightSecondaryContainer = Color(0xFFD5E3FF)
private val lightOnSecondaryContainer = Color(0xFF001C3B)
private val lightTertiary = Color(0xFF804893)
private val lightOnTertiary = Color(0xFFFFFFFF)
private val lightTertiaryContainer = Color(0xFFFAD7FF)
private val lightOnTertiaryContainer = Color(0xFF330045)
private val lightError = Color(0xFFBA1A1A)
private val lightErrorContainer = Color(0xFFFFDAD6)
private val lightOnError = Color(0xFFFFFFFF)
private val lightOnErrorContainer = Color(0xFF410002)
private val lightBackground = Color(0xFFFDFBFF)
private val lightOnBackground = Color(0xFF1A1B1E)
private val lightSurface = Color(0xFFFDFBFF)
private val lightOnSurface = Color(0xFF1A1B1E)
private val lightSurfaceVariant = Color(0xFFE0E2EC)
private val lightOnSurfaceVariant = Color(0xFF40434A)
private val lightOutline = Color(0xFF5C5F67)
private val lightInverseOnSurface = Color(0xFFF0F0F7)
private val lightInverseSurface = Color(0xFF2E3036)
private val lightInversePrimary = Color(0xFFA9C7FF)
private val lightSurfaceTint = Color(0xFF275EA7)
private val lightOutlineVariant = Color(0xFFC4C6CF)
private val lightScrim = Color(0xFF000000)
private val lightSurfaceBright = Color(0xFFF9F9FF)
private val lightSurfaceDim = Color(0xFFD9D9E0)
private val lightSurfaceContainerLowest = Color(0xFFFDFDFD)
private val lightSurfaceContainerLow = Color(0xFFF3F3FA)
private val lightSurfaceContainer = Color(0xFFEDEDF4)
private val lightSurfaceContainerHigh = Color(0xFFE7E8EE)
private val lightSurfaceContainerHighest = Color(0xFFE0E2EC)

private val darkPrimary = Color(0xFFA9C7FF)
private val darkOnPrimary = Color(0xFF003063)
private val darkPrimaryContainer = Color(0xFF00468B)
private val darkOnPrimaryContainer = Color(0xFFD6E3FF)
private val darkSecondary = Color(0xFFA7C8FF)
private val darkOnSecondary = Color(0xFF000000)
private val darkSecondaryContainer = Color(0xFF004787)
private val darkOnSecondaryContainer = Color(0xFFD5E3FF)
private val darkTertiary = Color(0xFFEEB1FF)
private val darkOnTertiary = Color(0xFF4D1661)
private val darkTertiaryContainer = Color(0xFF662F79)
private val darkOnTertiaryContainer = Color(0xFFFAD7FF)
private val darkError = Color(0xFFFFB4AB)
private val darkErrorContainer = Color(0xFF93000A)
private val darkOnError = Color(0xFF690005)
private val darkOnErrorContainer = Color(0xFFFFDAD6)
private val darkBackground = Color(0xFF111318)
private val darkOnBackground = Color(0xFFFBFAFF)
private val darkSurface = Color(0xFF111318)
private val darkOnSurface = Color(0xFFFBFAFF)
private val darkSurfaceVariant = Color(0xFF44474E)
private val darkOnSurfaceVariant = Color(0xFFC4C6CF)
private val darkOutline = Color(0xFF8E9099)
private val darkInverseOnSurface = Color(0xFF1A1B1E)
private val darkInverseSurface = Color(0xFFE3E2E6)
private val darkInversePrimary = Color(0xFF275EA7)
private val darkSurfaceTint = Color(0xFFA9C7FF)
private val darkOutlineVariant = Color(0xFF44474E)
private val darkScrim = Color(0xFF000000)
private val darkSurfaceBright = Color(0xFF37393E)
private val darkSurfaceDim = Color(0xFF111318)
private val darkSurfaceContainerLowest = Color(0xFF0C0E13)
private val darkSurfaceContainerLow = Color(0xFF191C20)
private val darkSurfaceContainer = Color(0xFF1D2024)
private val darkSurfaceContainerHigh = Color(0xFF282A2F)
private val darkSurfaceContainerHighest = Color(0xFF33353A)

val WoofwoofLightColorScheme = lightColorScheme(
    primary = lightPrimary,
    onPrimary = lightOnPrimary,
    primaryContainer = lightPrimaryContainer,
    onPrimaryContainer = lightOnPrimaryContainer,
    secondary = lightSecondary,
    onSecondary = lightOnSecondary,
    secondaryContainer = lightSecondaryContainer,
    onSecondaryContainer = lightOnSecondaryContainer,
    tertiary = lightTertiary,
    onTertiary = lightOnTertiary,
    tertiaryContainer = lightTertiaryContainer,
    onTertiaryContainer = lightOnTertiaryContainer,
    error = lightError,
    errorContainer = lightErrorContainer,
    onError = lightOnError,
    onErrorContainer = lightOnErrorContainer,
    background = lightBackground,
    onBackground = lightOnBackground,
    surface = lightSurface,
    onSurface = lightOnSurface,
    surfaceVariant = lightSurfaceVariant,
    onSurfaceVariant = lightOnSurfaceVariant,
    outline = lightOutline,
    inverseOnSurface = lightInverseOnSurface,
    inverseSurface = lightInverseSurface,
    inversePrimary = lightInversePrimary,
    surfaceTint = lightSurfaceTint,
    outlineVariant = lightOutlineVariant,
    scrim = lightScrim,
    surfaceBright = lightSurfaceBright,
    surfaceContainer = lightSurfaceContainer,
    surfaceContainerHigh = lightSurfaceContainerHigh,
    surfaceContainerHighest = lightSurfaceContainerHighest,
    surfaceContainerLow = lightSurfaceContainerLow,
    surfaceContainerLowest = lightSurfaceContainerLowest,
    surfaceDim = lightSurfaceDim
)

val WoofwoofDarkColorScheme = darkColorScheme(
    primary = darkPrimary,
    onPrimary = darkOnPrimary,
    primaryContainer = darkPrimaryContainer,
    onPrimaryContainer = darkOnPrimaryContainer,
    secondary = darkSecondary,
    onSecondary = darkOnSecondary,
    secondaryContainer = darkSecondaryContainer,
    onSecondaryContainer = darkOnSecondaryContainer,
    tertiary = darkTertiary,
    onTertiary = darkOnTertiary,
    tertiaryContainer = darkTertiaryContainer,
    onTertiaryContainer = darkOnTertiaryContainer,
    error = darkError,
    errorContainer = darkErrorContainer,
    onError = darkOnError,
    onErrorContainer = darkOnErrorContainer,
    background = darkBackground,
    onBackground = darkOnBackground,
    surface = darkSurface,
    onSurface = darkOnSurface,
    surfaceVariant = darkSurfaceVariant,
    onSurfaceVariant = darkOnSurfaceVariant,
    outline = darkOutline,
    inverseOnSurface = darkInverseOnSurface,
    inverseSurface = darkInverseSurface,
    inversePrimary = darkInversePrimary,
    surfaceTint = darkSurfaceTint,
    outlineVariant = darkOutlineVariant,
    scrim = darkScrim,
    surfaceBright = darkSurfaceBright,
    surfaceContainer = darkSurfaceContainer,
    surfaceContainerHigh = darkSurfaceContainerHigh,
    surfaceContainerHighest = darkSurfaceContainerHighest,
    surfaceContainerLow = darkSurfaceContainerLow,
    surfaceContainerLowest = darkSurfaceContainerLowest,
    surfaceDim = darkSurfaceDim
)

object VibrantColor {
    val red = Color(0xFFE21B3C)
    val blue = Color(0xFF1368CE)
    val green = Color(0xFF26890C)
    val yellow = Color(0xFFFFA602)
}
