package com.tijiebo.woofwoof.model

import androidx.annotation.Keep
import com.tijiebo.woofwoof.R

@Keep
enum class DogBreed(val title: String, val code: String, val drawableResId: Int) {
    AFFENPINSCHER("Affenpinscher", "affenpinscher", R.drawable.img_affenpinscher),
    AFRICAN("African", "african", R.drawable.img_african),
    AIREDALE("Airedale", "airedale", R.drawable.img_airedale),
    AKITA("Akita", "akita", R.drawable.img_akita),
    APPENZELLER("Appenzeller", "appenzeller", R.drawable.img_appenzeller),
    AUSTRALIAN_KELPIE("Australian Kelpie", "australian/kelpie", R.drawable.img_australian_kelpie),
    AUSTRALIAN_SHEPHERD("Australian Shepherd", "australian/shepherd", R.drawable.img_australian_shepherd),
    INDIAN_BAKHARWAL("Indian Bakharwal", "bakharwal/indian", R.drawable.img_bakharwal_indian),
    BASENJI("Basenji", "basenji", R.drawable.img_basenji),
    BEAGLE("Beagle", "beagle", R.drawable.img_beagle),
    BLUETICK("Bluetick", "bluetick", R.drawable.img_bluetick),
    BORZOI("Borzoi", "borzoi", R.drawable.img_borzoi),
    BOUVIER("Bouvier", "bouvier", R.drawable.img_bouvier),
    BOXER("Boxer", "boxer", R.drawable.img_boxer),
    BRABANCON("Brabancon", "brabancon", R.drawable.img_brabancon),
    BRIARD("Briard", "briard", R.drawable.img_briard),
    NORWEGIAN_BUHUND("Norwegian Buhund", "buhund/norwegian", R.drawable.img_buhund_norwegian),
    BOSTON_BULLDOG("Boston Bulldog", "bulldog/boston", R.drawable.img_bulldog_boston),
    ENGLISH_BULLDOG("English Bulldog", "bulldog/english", R.drawable.img_bulldog_english),
    FRENCH_BULLDOG("French Bulldog", "bulldog/french", R.drawable.img_bulldog_french),
    STAFFORDSHIRE_BULLTERRIER("Staffordshire Bullterrier", "bullterrier/staffordshire", R.drawable.img_bullterrier_staffordshire),
    AUSTRALIAN_CATTLEDOG("Australian Cattledog", "cattledog/australian", R.drawable.img_cattledog_australian),
    CAVAPOO("Cavapoo", "cavapoo", R.drawable.img_cavapoo),
    CHIHUAHUA("Chihuahua", "chihuahua", R.drawable.img_chihuahua),
    INDIAN_CHIPPIPARAI("Indian Chippiparai", "chippiparai/indian", R.drawable.img_chippiparai_indian),
    CHOW("Chow", "chow", R.drawable.img_chow),
    CLUMBER("Clumber", "clumber", R.drawable.img_clumber),
    COCKAPOO("Cockapoo", "cockapoo", R.drawable.img_cockapoo),
    BORDER_COLLIE("Border Collie", "collie/border", R.drawable.img_collie_border),
    COONHOUND("Coonhound", "coonhound", R.drawable.img_coonhound),
    CARDIGAN_CORGI("Cardigan Corgi", "corgi/cardigan", R.drawable.img_corgi_cardigan),
    COTONDETULEAR("Cotondetulear", "cotondetulear", R.drawable.img_cotondetulear),
    DACHSHUND("Dachshund", "dachshund", R.drawable.img_dachshund),
    DALMATIAN("Dalmatian", "dalmatian", R.drawable.img_dalmatian),
    GREAT_DANE("Great Dane", "dane/great", R.drawable.img_dane_great),
    SWEDISH_DANISH("Swedish Danish", "danish/swedish", R.drawable.img_danish_swedish),
    SCOTTISH_EERHOUND("Scottish Deerhound", "deerhound/scottish", R.drawable.img_deerhound_scottish),
    DHOLE("Dhole", "dhole", R.drawable.img_dhole),
    DINGO("Dingo", "dingo", R.drawable.img_dingo),
    DOBERMAN("Doberman", "doberman", R.drawable.img_doberman),
    NORWEGIAN_ELKHOUND("Norwegian Elkhound", "elkhound/norwegian", R.drawable.img_elkhound_norwegian),
    ENTLEBUCHER("Entlebucher", "entlebucher", R.drawable.img_entlebucher),
    ESKIMO("Eskimo", "eskimo", R.drawable.img_eskimo),
    FINNISH_LAPPHUND(" Finnish Lapphund", "finnish/lapphund", R.drawable.img_finnish_lapphund),
    BICHON_FRISE("Bichon Frise", "frise/bichon", R.drawable.img_frise_bichon),
    INDIAN_GADDI("Indian Gaddi", "gaddi/indian", R.drawable.img_gaddi_indian),
    GERMANSHEPHERD("Germanshepherd", "germanshepherd", R.drawable.img_germanshepherd),
    INDIAN_GREYHOUND("Indian Greyhound", "greyhound/indian", R.drawable.img_greyhound_indian),
    ITALIAN_GREYHOUND("Italian Greyhound", "greyhound/italian", R.drawable.img_greyhound_italian),
    GROENENDAEL("Groenendael", "groenendael", R.drawable.img_groenendael),
    HAVANESE("Havanese", "havanese", R.drawable.img_havanese),
    AFGHAN_HOUND("Afghan Hound", "hound/afghan", R.drawable.img_hound_afghan),
    BASSET_HOUND("Basset Hound", "hound/basset", R.drawable.img_hound_basset),
    BLOOD_HOUND("Blood Hound", "hound/blood", R.drawable.img_hound_blood),
    ENGLISH_HOUND("English Hound", "hound/english", R.drawable.img_hound_english),
    IBIZAN_HOUND("Ibizan Hound", "hound/ibizan", R.drawable.img_hound_ibizan),
    PLOTT_HOUND("Plott Hound", "hound/plott", R.drawable.img_hound_plott),
    WALKER_HOUND("Walker Hound", "hound/walker", R.drawable.img_hound_walker),
    HUSKY("Husky", "husky", R.drawable.img_husky),
    KEESHOND("Keeshond", "keeshond", R.drawable.img_keeshond),
    KELPIE("Kelpie", "kelpie", R.drawable.img_kelpie),
    KOMBAI("Kombai", "kombai", R.drawable.img_kombai),
    KOMONDOR("Komondor", "komondor", R.drawable.img_komondor),
    KUVASZ("Kuvasz", "kuvasz", R.drawable.img_kuvasz),
    LABRADOODLE("Labradoodle", "labradoodle", R.drawable.img_labradoodle),
    LABRADOR("Labrador", "labrador", R.drawable.img_labrador),
    LEONBERG("Leonberg", "leonberg", R.drawable.img_leonberg),
    LHASA("Lhasa", "lhasa", R.drawable.img_lhasa),
    MALAMUTE("Malamute", "malamute", R.drawable.img_malamute),
    MALINOIS("Malinois", "malinois", R.drawable.img_malinois),
    MALTESE("Maltese", "maltese", R.drawable.img_maltese),
    BULL_MASTIFF("Bull Mastiff", "mastiff/bull", R.drawable.img_mastiff_bull),
    ENGLISH_MASTIFF("English Mastiff", "mastiff/english", R.drawable.img_mastiff_english),
    INDIAN_MASTIFF("Indian Mastiff", "mastiff/indian", R.drawable.img_mastiff_indian),
    TIBETAN_MASTIFF("Tibetan Mastiff", "mastiff/tibetan", R.drawable.img_mastiff_tibetan),
    MEXICANHAIRLESS("Mexicanhairless", "mexicanhairless", R.drawable.img_mexicanhairless),
    MIX("Mix", "mix", R.drawable.img_mix),
    BERNESE_MOUNTAIN("Bernese Mountain", "mountain/bernese", R.drawable.img_mountain_bernese),
    SWISS_MOUNTAIN("Swiss Mountain", "mountain/swiss", R.drawable.img_mountain_swiss),
    INDIAN_MUDHOL("Indian Mudhol", "mudhol/indian", R.drawable.img_mudhol_indian),
    NEWFOUNDLAND("Newfoundland", "newfoundland", R.drawable.img_newfoundland),
    OTTERHOUND("Otterhound", "otterhound", R.drawable.img_otterhound),
    CAUCASIAN_OVCHARKA("Caucasian Ovcharka", "ovcharka/caucasian", R.drawable.img_ovcharka_caucasian),
    PAPILLON("Papillon", "papillon", R.drawable.img_papillon),
    INDIAN_PARIAH("Indian Pariah", "pariah/indian", R.drawable.img_pariah_indian),
    PEKINESE("Pekinese", "pekinese", R.drawable.img_pekinese),
    PEMBROKE("Pembroke", "pembroke", R.drawable.img_pembroke),
    MINIATURE_PINSCHER("Miniature Pinscher", "pinscher/miniature", R.drawable.img_pinscher_miniature),
    PITBULL("Pitbull", "pitbull", R.drawable.img_pitbull),
    GERMAN_POINTER("German Pointer", "pointer/german", R.drawable.img_pointer_german),
    GERMANLONGHAIR_POINTER("Germanlonghair Pointer", "pointer/germanlonghair", R.drawable.img_pointer_germanlonghair),
    POMERANIAN("Pomeranian", "pomeranian", R.drawable.img_pomeranian),
    MEDIUM_POODLE("Medium Poodle", "poodle/medium", R.drawable.img_poodle_medium),
    MINIATURE_POODLE("Miniature Poodle", "poodle/miniature", R.drawable.img_poodle_miniature),
    STANDARD_POODLE("Standard Poodle", "poodle/standard", R.drawable.img_poodle_standard),
    TOY_POODLE("Toy Poodle", "poodle/toy", R.drawable.img_poodle_toy),
    PUG("Pug", "pug", R.drawable.img_pug),
    PUGGLE("Puggle", "puggle", R.drawable.img_puggle),
    PYRENEES("Pyrenees", "pyrenees", R.drawable.img_pyrenees),
    INDIAN_RAJAPALAYAM("Indian Rajapalayam", "rajapalayam/indian", R.drawable.img_rajapalayam_indian),
    REDBONE("Redbone", "redbone", R.drawable.img_redbone),
    CHESAPEAKE_RETRIEVER("Chesapeake Retriever", "retriever/chesapeake", R.drawable.img_retriever_chesapeake),
    CURLY_RETRIEVER("Curly Retriever", "retriever/curly", R.drawable.img_retriever_curly),
    FLATCOATED_RETRIEVER("Flatcoated Retriever", "retriever/flatcoated", R.drawable.img_retriever_flatcoated),
    GOLDEN_RETRIEVER("Golden Retriever", "retriever/golden", R.drawable.img_retriever_golden),
    RHODESIAN_RIDGEBACK("Rhodesian Ridgeback", "ridgeback/rhodesian", R.drawable.img_ridgeback_rhodesian),
    ROTTWEILER("Rottweiler", "rottweiler", R.drawable.img_rottweiler),
    SALUKI("Saluki", "saluki", R.drawable.img_saluki),
    SAMOYED("Samoyed", "samoyed", R.drawable.img_samoyed),
    SCHIPPERKE("Schipperke", "schipperke", R.drawable.img_schipperke),
    GIANT_SCHNAUZER("Giant Schnauzer", "schnauzer/giant", R.drawable.img_schnauzer_giant),
    MINIATURE_SCHNAUZER("Miniature Schnauzer", "schnauzer/miniature", R.drawable.img_schnauzer_miniature),
    ITALIAN_SEGUGIO("Italian Segugio", "segugio/italian", R.drawable.img_segugio_italian),
    ENGLISH_SETTER("English Setter", "setter/english", R.drawable.img_setter_english),
    GORDON_SETTER("Gordon Setter", "setter/gordon", R.drawable.img_setter_gordon),
    IRISH_SETTER("Irish Setter", "setter/irish", R.drawable.img_setter_irish),
    SHARPEI("Sharpei", "sharpei", R.drawable.img_sharpei),
    ENGLISH_SHEEPDOG("English Sheepdog", "sheepdog/english", R.drawable.img_sheepdog_english),
    INDIAN_SHEEPDOG("Indian Sheepdog", "sheepdog/indian", R.drawable.img_sheepdog_indian),
    SHETLAND_SHEEPDOG("Shetland Sheepdog", "sheepdog/shetland", R.drawable.img_sheepdog_shetland),
    SHIBA("Shiba", "shiba", R.drawable.img_shiba),
    SHIHTZU("Shihtzu", "shihtzu", R.drawable.img_shihtzu),
    BLENHEIM_SPANIEL("Blenheim Spaniel", "spaniel/blenheim", R.drawable.img_spaniel_blenheim),
    BRITTANY_SPANIEL("Brittany Spaniel", "spaniel/brittany", R.drawable.img_spaniel_brittany),
    COCKER_SPANIEL("Cocker Spaniel", "spaniel/cocker", R.drawable.img_spaniel_cocker),
    IRISH_SPANIEL("Irish Spaniel", "spaniel/irish", R.drawable.img_spaniel_irish),
    JAPANESE_SPANIEL("Japanese Spaniel", "spaniel/japanese", R.drawable.img_spaniel_japanese),
    SUSSEX_SPANIEL("Sussex Spaniel", "spaniel/sussex", R.drawable.img_spaniel_sussex),
    WELSH_SPANIEL("Welsh Spaniel", "spaniel/welsh", R.drawable.img_spaniel_welsh),
    INDIAN_SPITZ("Indian Spitz", "spitz/indian", R.drawable.img_spitz_indian),
    JAPANESE_SPITZ("Japanese Spitz", "spitz/japanese", R.drawable.img_spitz_japanese),
    ENGLISH_SPRINGER("English Springer", "springer/english", R.drawable.img_springer_english),
    STBERNARD("Stbernard", "stbernard", R.drawable.img_stbernard),
    AMERICAN_TERRIER("American Terrier", "terrier/american", R.drawable.img_terrier_american),
    AUSTRALIAN_TERRIER("Australian Terrier", "terrier/australian", R.drawable.img_terrier_australian),
    BEDLINGTON_TERRIER("Bedlington Terrier", "terrier/bedlington", R.drawable.img_terrier_bedlington),
    BORDER_TERRIER("Border Terrier", "terrier/border", R.drawable.img_terrier_border),
    CAIRN_TERRIER("Cairn Terrier", "terrier/cairn", R.drawable.img_terrier_cairn),
    DANDIE_TERRIER("Dandie Terrier", "terrier/dandie", R.drawable.img_terrier_dandie),
    FOX_TERRIER("Fox Terrier", "terrier/fox", R.drawable.img_terrier_fox),
    IRISH_TERRIER("Irish Terrier", "terrier/irish", R.drawable.img_terrier_irish),
    KERRYBLUE_TERRIER("Kerryblue Terrier", "terrier/kerryblue", R.drawable.img_terrier_kerryblue),
    LAKELAND_TERRIER("Lakeland Terrier", "terrier/lakeland", R.drawable.img_terrier_lakeland),
    NORFOLK_TERRIER("Norfolk Terrier", "terrier/norfolk", R.drawable.img_terrier_norfolk),
    NORWICH_TERRIER("Norwich Terrier", "terrier/norwich", R.drawable.img_terrier_norwich),
    PATTERDALE_TERRIER("Patterdale Terrier", "terrier/patterdale", R.drawable.img_terrier_patterdale),
    RUSSELL_TERRIER("Russell Terrier", "terrier/russell", R.drawable.img_terrier_russell),
    SCOTTISH_TERRIER("Scottish Terrier", "terrier/scottish", R.drawable.img_terrier_scottish),
    SEALYHAM_TERRIER("Sealyham Terrier", "terrier/sealyham", R.drawable.img_terrier_sealyham),
    SILKY_TERRIER("Silky Terrier", "terrier/silky", R.drawable.img_terrier_silky),
    TIBETAN_TERRIER("Tibetan Terrier", "terrier/tibetan", R.drawable.img_terrier_tibetan),
    TOY_TERRIER("Toy Terrier", "terrier/toy", R.drawable.img_terrier_toy),
    WELSH_TERRIER("Welsh Terrier", "terrier/welsh", R.drawable.img_terrier_welsh),
    WESTHIGHLAND_TERRIER("Westhighland Terrier", "terrier/westhighland", R.drawable.img_terrier_westhighland),
    WHEATEN_TERRIER("Wheaten Terrier", "terrier/wheaten", R.drawable.img_terrier_wheaten),
    YORKSHIRE_TERRIER("Yorkshire Terrier", "terrier/yorkshire", R.drawable.img_terrier_yorkshire),
    TERVUREN("Tervuren", "tervuren", R.drawable.img_tervuren),
    VIZSLA("Vizsla", "vizsla", R.drawable.img_vizsla),
    SPANISH_WATERDOG("Spanish Waterdog", "waterdog/spanish", R.drawable.img_waterdog_spanish),
    WEIMARANER("Weimaraner", "weimaraner", R.drawable.img_weimaraner),
    WHIPPET("Whippet", "whippet", R.drawable.img_whippet),
    IRISH_WOLFHOUND("Irish Wolfhound", "wolfhound/irish", R.drawable.img_wolfhound_irish)
}
